# Generated by Django 3.2.25 on 2024-10-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
